# Configure this Discovery Server
eureka:
  instance:
    hostname: microservicediscoveryserve
  client: 
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: 8080   
